name: inspec-git-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 6
      matrix:
        TAG_NAME: [ubuntu-18.04, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install InSpec
      run: |
        gem install inspec
    - name: Running Inspec Profile: Git
      run: |
        inspec exec .
